"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./user.model");
require("./track.model");
require("./inventory.model");
require("./category.model");
require("./status.model");
require("./usage.model");
require("./log.model");
const inventory_model_1 = require("./inventory.model");
const inventory_check_model_1 = require("./inventory-check.model");
const user_model_1 = require("./user.model");
const category_model_1 = require("./category.model");
const status_model_1 = require("./status.model");
const usage_model_1 = require("./usage.model");
inventory_model_1.Inventory.belongsTo(user_model_1.User, { foreignKey: 'userId' });
inventory_model_1.Inventory.belongsTo(category_model_1.Category, { foreignKey: 'categoryId' });
inventory_model_1.Inventory.belongsTo(status_model_1.Status, { foreignKey: 'statusId' });
inventory_model_1.Inventory.belongsTo(usage_model_1.Usage, { foreignKey: 'usageId' });
user_model_1.User.hasMany(inventory_model_1.Inventory, { foreignKey: 'userId' });
category_model_1.Category.hasMany(inventory_model_1.Inventory, { foreignKey: 'categoryId' });
status_model_1.Status.hasMany(inventory_model_1.Inventory, { foreignKey: 'statusId' });
usage_model_1.Usage.hasMany(inventory_model_1.Inventory, { foreignKey: 'usageId' });
inventory_check_model_1.InventoryCheck.belongsTo(inventory_model_1.Inventory, { foreignKey: 'inventoryId' });
inventory_model_1.Inventory.hasMany(inventory_check_model_1.InventoryCheck, { foreignKey: 'inventoryId' });
