# fly.toml app configuration file generated for ms-stock-it on 2024-04-24T17:45:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ms-stock-it'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
